name: 'action-on-push'
on:
  push: 
    branches-ignore:
      - main

permissions:
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  
jobs:
  init:
    name: init
    runs-on: ubuntu-latest
    
    outputs:
      folders: ${{ steps.diff.outputs.folders }}
      modules: ${{ steps.diff-modules.outputs.modules }}
      plan-modules: ${{ steps.plan-modules.outputs.planModules }}
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set output list of all new/modified folders 
      id: diff
      run: |
        diffFolders=$( find -name "*.tf" | grep -E "^.*/.*/.*$" | xargs dirname | uniq | grep -v ".terraform" | grep -v "/IaC/modules" | jq  -cnR '[inputs | select(length>0)]')
        echo "JSON of all new or modifed folders: \n $diffFolders"
        echo "::set-output name=folders::${diffFolders}"
    
    - name: Set output list of all new/modified modules 
      id: diff-modules
      run: |
        diffModules=$( find -name "*.tf" | grep -E "^.*/.*/.*$" | xargs dirname | uniq | grep -v ".terraform" | grep "/IaC/modules" | tr '\n' ',')
        echo "JSON of all new or modifed Module: \n $diffModules"
        echo "::set-output name=modules::${diffModules}"
    
    - name: Set output list of all modules to test with plan
      id: plan-modules
      run: |
        planModules=$( find -name "*.tf" | grep -E "^.*/.*/.*$" | xargs dirname | uniq | grep -v ".terraform" | grep "/IaC/modules" | jq  -cnR '[inputs | select(length>0)]')
        echo "JSON of all new or modifed Module: \n $planModules"
        echo "::set-output name=planModules::${planModules}"

    
  readme-generation:
    name: 'readme-generation'
    runs-on: ubuntu-latest
    needs: [init]
    environment: production

    strategy:
      fail-fast: true

    steps:
    # Pull the latest changes
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.push_request.head.ref }}
        token: ${{ secrets.GH_TOKEN }}

    # Check required docs update for each module
    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: ${{ needs.init.outputs.modules }}
        output-file: README.md
        output-method: inject
        git-push: "true"
        config-file: ../docs_config.yml
        git-commit-message: "Automatic documentation update"

############

  check-modules:
    name: 'check-modules'
    runs-on: ubuntu-latest
    needs: [init,readme-generation]
    environment: production
    
    # foreach folder from init job run this job 
    strategy:
      # if one of the jobs is failling - still continue to run all of the others 
      fail-fast: false
      matrix: 
        folder: ${{ fromJson(needs.init.outputs.plan-modules) }}
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.folder }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: cd
      run: |
        echo "${{ matrix.folder }}"
        cd ${{ matrix.folder }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    - name: Create provider file 
      id: provider
      run: |
        echo "provider "azurerm" {  
          features {}
        }" >> provider.tf
    
    - name: Terraform Plan
      run: terraform plan -var-file=terraform.tfvars.test

############
  terraform-validate:
    name: 'Terraform-validate'
    runs-on: ubuntu-latest
    needs: [init,readme-generation]
    environment: production
    
    # foreach folder from init job run this job 
    strategy:
      # if one of the jobs is failling - still continue to run all of the others 
      fail-fast: false
      matrix: 
        folder: ${{ fromJson(needs.init.outputs.folders) }}
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.folder }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false

